spring:
  application:
    name: Butter-Salt-Flour-BE
  datasource:
    url: jdbc:postgresql://db.fsiqzzipdabcjqouqkzq.supabase.co:5432/postgres
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: create
gemini:
  service:
    endpoint: ${GEMINAI_ENDPOINT}
    apikey: ${GEMINAI_APIKEY}